
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  template:
    metadata:
      annotations:
        checksum/image: {{ .Values.image.hash }}
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      volumes:
      - name: aidbox-secret-files
        secret:
          secretName: {{ template "secretname" . }}
          items:
          - key: KEY_OPENID_RSA
            path: jwtRS256.key
          - key: KEY_OPENID_RSA_PUB
            path: jwtRS256.key.pub
      - name: bucket-secret-files
        secret:
          secretName: {{ .Release.Name }}-bucket
          items:
          - key: BUCKET_GCE_KEY
            path: service-account.json
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{ end }}
        env:
        - name: PGHOST
          value: {{ template "aidboxdb.fullname" . }}
        - name: PGPORT
          value: "5432"

        - name: POSTGRES_DB
          value: fhir_emr
        - name: PGDATABASE
          value: fhir_emr

        - name: AIDBOX_PORT
          value: "{{ .Values.service.internalPort }}"
        - name: AIDBOX_FHIR_VERSION
          value: "4.0.0"
        - name: OPENID_RSA
          value: /var/config/jwtRS256.key
        - name: OPENID_RSA_PUB
          value: /var/config/jwtRS256.key.pub
        - name: BUCKET_ACCOUNT_PATH
          value: /var/bucket-config/service-account.json
        - name: BUCKET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-bucket
              key: BUCKET
        envFrom:
        - secretRef:
            name: {{ template "secretname" . }}
        volumeMounts:
        - name:  aidbox-secret-files
          mountPath: "/var/config"
          readOnly: true
        - name:  bucket-secret-files
          mountPath: "/var/bucket-config"
          readOnly: true
        ports:
        - containerPort: {{ .Values.service.internalPort }}

